server:
  port: 8080
  servlet:
    context-path: /exemplo
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: gestoc01
    url: jdbc:oracle:thin:@10.21.1.1:1521:treino
    username: gestoc
usa:
  filtro:
    seguranca: true
