server:
  port: 8080
  servlet:
    context-path: /${artifactId}
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: senha
    url: jdbc:oracle:thin:@IP:1521:SID
    username: usuario
usa:
  filtro:
    seguranca: true
